version: '3.7'
services:
  web:
    build: ./project
    command: gunicorn -b 0.0.0.0:8000 -w 4 -k uvicorn.workers.UvicornWorker app.main:app 
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8000:8000
